/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * `code` on the `Error` a failed conversion rejects with. Conversion fails
 * only when no meaningful Markdown could be produced; producer quirks are
 * recovered or skipped instead.
 */
export type ConvertErrorCode =
  /** Unknown format, or one that cannot be converted (an image-only PDF). */
  | 'unsupported'
  /** Structurally unusable: no meaningful content could be extracted. */
  | 'malformed'
  /** Encrypted or password-protected. */
  | 'encrypted'
  /** Crossed a fixed safety limit (decompression, nesting, node count). */
  | 'resourceLimit'
  /** A part required for any meaningful output is absent. */
  | 'missingPart'
  /** The file could not be read, from `toMarkdown` only. */
  | 'io'
